apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-debian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debug-debian
  template:
    metadata:
      labels:
        app: debug-debian
    spec:
      containers:
      - name: debug-container
        image: debian:12
        command: ["/bin/bash"]
        stdin: true
        tty: true
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-c", "apt update && apt install -y iputils-ping dnsutils curl telnet"]
